name: push-action
description: description
inputs:
  docker_username:
    description: "Docker username."
    required: false
  image_name:
    description: "Specifies the name for the generated Docker image."
    required: false
runs:
  using: composite
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ inputs.docker_username }}/${{ inputs.image_name }}:latest


