name: Academy Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: RodrigoFAbreu/academy/.github/action/docker_build@main
    - name: List Docker images  
      run: docker images
