name: Academy Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: RodrigoFAbreu/academy/.github/action/docker_build@main
        with:
          tag_name: 1.0.0
          path_dockerfile: Dockerfile
          image_name: academy
      - name: List Docker images
        run: docker images
      - name: Login DockerHub
        uses: RodrigoFAbreu/academy/.github/action/docker_build@push-action
        with:
          docker_username: rodrigoabreu587
          image_name: academy
